### ISSUE TITLE
Support for Razer BlackWidow Elite Keyboard

### ISSUE THREAD

**Issue by kpmarcin** [tdakhran/razer-ctl#5]
Hello,

Would it be possible to include support for Razer BlackWidow Elite keyboard?
Thanks a lot!

C:\Users\Marcin\Downloads>razer-cli.exe enumerate
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0306, manufacturer: , product:  }
RazerDevice { vid: 0x1532, pid: 0x0306, manufacturer: , product:  }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: Razer, product: Razer BlackWidow Elite }
RazerDevice { vid: 0x1532, pid: 0x0228, manufacturer: , product:  }

C:\Users\Marcin\Downloads>
C:\Users\Marcin\Downloads>razer-cli.exe backlight 100
Error: hidapi error: No HID devices with requested VID/PID found in the system.
C:\Users\Marcin\Downloads>razer-cli.exe -p 0x0228 info
Error: hidapi error: HidD_SetFeature: (0x00000001) Incorrect function.

C:\Users\Marcin\Downloads>

Kind regards,
Marcin.

**Comment by tdakhran** [comment]
Razer Synapse consists of multiple modules, and I believe the keyboard is controlled by the Razer Chroma module. The application intends to control the Laptop.

The reverse engineering steps described here might work for the external keyboard as well, but that's another project.
