### ISSUE TITLE
Possibility to set integrated graphics only mode

### ISSUE THREAD

**Issue by 2956694624** [tdakhran/razer-ctl#7]
Razer blade 14 2023 
I've been trying to get this laptop to use only the integrated graphics mode when using the battery to enhance the endurance

**Comment by tdakhran** [comment]
Setting integrated graphics only is not controlled by Razer software, but rather by Windows itself via Nvidia drivers.
The question is not related to the program.

Let me share my experience.

Mine blade 16 2023 always uses a discrete GPU when an external display is connected.
However, when you are on battery and have no external displays, things become more interesting.
I use HWiNFO64 to check the power consumption of the discrete GPU and Nvidia Container to see which applications are running on the discrete GPU.

Once the following conditions are met, Windows puts  Nvidia GPU into power save mode and it consumes no power.

- No external display connected
- No app running on Nvidia GPU

If the app is still running on Nvidia GPU (shown in Nvidia Container), then you need to restart it.

Here is on battery with apps using GPU
<img width="386" alt="image" src="https://github.com/tdakhran/razer-ctl/assets/20753751/19df8372-84aa-47a9-ab27-08d73fc02c97">

Once I close/restart them I get
<img width="386" alt="image" src="https://github.com/tdakhran/razer-ctl/assets/20753751/2f7fc51f-4085-4432-a1d6-e60f319fbcd1">

Which shows power consumption for

- discrete GPU is **0W**
- CPU is **4.54W**
- Total is **11W**

This mode gives me ~5 hours of battery life.

**Comment by 2956694624** [comment]
I have also learned this method, which uses the integrated graphics card for rendering in most software, except for occasional application startups that use the discrete GPU for rendering. There is an increase in power consumption of about 10 seconds, which then decreases to 0. The current battery life has also increased to 5 hours, which is very effective!
